services:
  reminder:
    image: ghcr.io/mygaga2024/reminder:latest
    container_name: reminder
    restart: always
    ports:
      - "35015:5000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - WX_APPID=wx25fb6f94762a07ea
      - WX_SECRET=556f18c8c34b12001287fab0d8e6187d
