services:
  reminder:
    # 强制拉取云端镜像
    image: ghcr.io/mygaga2024/reminder:v1.2.0
    # 强制锁死容器名，防止生成 reminder-reminder-1
    container_name: reminder
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data